blog/forms/article.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators, SubmitField, TextAreaField, SelectMultipleField


class CreateArticleForm(FlaskForm):
    title = StringField('Title', [validators.DataRequired()])
    text = TextAreaField('Text', [validators.DataRequired()])
    tags = SelectMultipleField('Tags', coerce=int)
    submit = SubmitField('Create')

blog/articles/views.py
from typing import Dict

import requests
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from sqlalchemy.orm import joinedload
from werkzeug.exceptions import NotFound

from blog.config import API_URL
from blog.extensions import db
from blog.forms.article import CreateArticleForm
from blog.models import Article, Author, Tag

article = Blueprint('article', __name__, url_prefix='/articles', static_folder='../static')


@article.route('/', methods=['GET'])
def article_list():
    articles: Article = Article.query.all()
    # call RPC method
    count_articles: Dict = requests.get(f'{API_URL}/api/articles/event_get_count/').json()
    return render_template(
        'articles/list.html',
        articles=articles,
        count_articles=count_articles['count'],

    )


@article.route('/<int:article_id>/', methods=['GET'])
def article_detail(article_id):
    _article: Article = Article.query.filter_by(
        id=article_id
    ).options(
        joinedload(Article.tags)
    ).one_or_none()

    if _article is None:
        raise NotFound
    return render_template(
        'articles/details.html',
        article=_article,
    )


@article.route('/create/', methods=['GET'])
@login_required
def create_article_form():
    form = CreateArticleForm(request.form)
    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by('name')]
    return render_template('articles/create.html', form=form)


@article.route('/', methods=['POST'])
@login_required
def create_article():
    form = CreateArticleForm(request.form)

    form.tags.choices = [(tag.id, tag.name) for tag in Tag.query.order_by('name')]

    if form.validate_on_submit():
        _article = Article(title=form.title.data.strip(), text=form.text.data)

        if current_user.author:
            _article.author_id = current_user.author.id
        else:
            author = Author(user_id=current_user.id)
            db.session.add(author)
            db.session.flush()
            _article.author_id = author.id

        if form.tags.data:
            selected_tags = Tag.query.filter(Tag.id.in_(form.tags.data))
            for tag in selected_tags:
                _article.tags.append(tag)

        db.session.add(_article)
        db.session.commit()

        return redirect(url_for('article.article_detail', article_id=_article.id))

    return render_template('articles/create.html', form=form)

blog/templates/articles/create.html
{% extends 'base.html' %}
{% from "macro/formhelpers.html" import render_field %}

{% block title %}
    Create article
{% endblock %}

{% block body %}
    <div class="row">
        <h1>Create article:</h1>
    </div>
    <form method="POST" action="{{ url_for('article.create_article') }}">
        {{ form.csrf_token }}
        {% for field in ['title', 'text', 'tags'] %}
            {{ render_field(form[field]) }}
        {% endfor %}

        {{ form.submit(class="btn btn-primary mb-3") }}
    </form>
{% endblock %}

blog/templates/articles/details.html
{% extends 'base.html' %}

{% block title %}
    {{ article.title }}
{% endblock %}

{% block body %}
    <div class="row">
        <h1>{{ article.title }}</h1>
    </div>
    <div class="row">
        <div class="col-md-12">{{ article.text }}</div>
    </div>

    <div class="row">
        <div class="col-6">
            <div><small class="text-muted">Author: {{ article.author.user.first_name }} {{ article.author.user.last_name }}</small></div>
            <div><small class="text-muted">Created at: {{ article.created_at.strftime('%d-%m-%Y %H:%M:%S') }}</small></div>
            <div><small class="text-muted">Updated at: {{ article.updated_at.strftime('%d-%m-%Y %H:%M:%S') }}</small></div>
        </div>
        <div class="col-6">
            {% for tag in article.tags %}
                <span class="badge bg-primary">{{ tag.name }}</span>
            {% endfor %}
        </div>
    </div>
{% endblock %}

blog/templates/articles/list.html
{% extends 'base.html' %}

{% block title %}
    Articles list
{% endblock %}

{% block body %}
    <div class="row">
        <h1>Articles (count: {{ count_articles }}, obtained from RPC call):</h1>
    </div>
    <div class="row row-cols-1 row-cols-md-4 g-4">
        {% for article in articles %}
            <div class="col">
                <div class="card h-100">
                    <div class="card-body">
                        <h5 class="card-title">{{ article.title }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">{{ article.author.user.first_name }} {{ article.author.user.last_name }}</h6>
                        <p class="card-text">{{ article.text | truncate(50) }}</p>
                        <a href="{{ url_for('article.article_detail', article_id=article.id) }}"
                           class="card-link">Read</a>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">Created at: {{ article.created_at.strftime('%d-%m-%Y %H:%M:%S') }}</small>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}